### ISSUE TITLE
ServerRequest parsedBody do not parse json

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-psr7bridge#1]
In Expressive is  `BodyParamsMiddleware` which handles body parsing (`x-www-form-urlencoded` and `json`). I think it would be useful to have same function in `Psr7ServerRequest`. I can create PR.

---

Originally posted by @vaclavvanik at https://github.com/zendframework/zend-psr7bridge/issues/36

**Comment by Xerkus** [comment]
Closing as such functionality would not belong here as this package is about converting request types between PSR-7 and laminas-http.
